# Generated by Django 4.2.4 on 2023-08-05 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Order'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Product'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='prouduct',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='staff',
        ),
    ]
